[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

gas_reports = ["APTFarm"]

[invariant]
runs = 64
depth = 256

# See more config options https://github.com/foundry-rs/foundry/tree/master/config